### ISSUE TITLE
npm build missing from package.json

### ISSUE THREAD

**Issue by jpkontreras** [vouill/vue-plugin-maker#1]
You missing license and contributing.MD too. 
I'm sorry for the inconvenience. Great package for starting. 
Thanks 👍

**Comment by vouill** [comment]
Thanks for the issue, i didnt know people actually used it haha. I ll spend some time today refreshing it and improving it then, thanks !

**Comment by vouill** [comment]
@jpkontreras Alright so i just updated the project.
- Fresh dependencies.
- Now minify the lib output  ( should have done that earlier )
- Uses jest as test runner.
- Uses vue-test-utils as test lib

Try to get latest changes, you will gain a lot regarding lib weight. If you happen to have trouble and cant easily pull the changes, just add [this](https://github.com/vouill/vue-plugin-maker/commit/26bcd152b5a0d95d49d445947e20dd659e3373ec#diff-ace37b232b3712f16abb67acf4f337d9R18) to your current config to gain significant lib size.
Also added a basic license and contributing.md too on your valid request.

However there is no `npm run build` on purpose. You can build the lib with `npm run build:lib` and build the example/app with `npm run build:docs`.

What do you expect from npm run build ?

**Comment by jpkontreras** [comment]
Thanks @vouill . I was just starting. So i will get a fresh clone. 
is there a way to make this a vue cli package ?

**Comment by vouill** [comment]
I honestly dont think the usage of this repo is high enough to be a vue-cli template, i will still look into it in my free time !
